use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::model::System;

pub(crate) fn write_topology(system: &System) -> String {
    let mut output = String::new();
    writeln!(output, "; Generated by GlySysBuilder").unwrap();
    writeln!(output, "[ defaults ]").unwrap();
    writeln!(output, "; nbfunc comb-rule gen-pairs fudgeLJ fudgeQQ").unwrap();
    writeln!(output, "1 2 yes 0.5 0.833333333333").unwrap();
    writeln!(output).unwrap();

    let types = system
        .atoms
        .iter()
        .map(|atom| (atom.atom_type.clone(), atom))
        .collect::<BTreeMap<_, _>>();
    writeln!(output, "[ atomtypes ]").unwrap();
    writeln!(
        output,
        "; name atomic_number mass charge ptype sigma(nm) epsilon(kJ/mol)"
    )
    .unwrap();
    for (name, atom) in types {
        let sigma_nm = 2.0 * atom.radius / 2.0f64.powf(1.0 / 6.0) / 10.0;
        let epsilon_kj = atom.epsilon * 4.184;
        writeln!(
            output,
            "{:<8} {:>3} {:>12.6} 0.0 A {:>14.8e} {:>14.8e}",
            name, atom.element, atom.mass, sigma_nm, epsilon_kj
        )
        .unwrap();
    }
    writeln!(output).unwrap();
    writeln!(output, "[ moleculetype ]").unwrap();
    writeln!(output, "PreparedSystem 3").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "[ atoms ]").unwrap();
    writeln!(output, "; nr type resnr residue atom cgnr charge mass").unwrap();
    for (index, atom) in system.atoms.iter().enumerate() {
        let residue = &system.residues[atom.residue];
        writeln!(
            output,
            "{:>7} {:<8} {:>7} {:<5} {:<5} {:>7} {:>14.8} {:>12.6} ; {}:{}{}",
            index + 1,
            atom.atom_type,
            atom.residue + 1,
            residue.name,
            atom.name,
            index + 1,
            atom.charge,
            atom.mass,
            residue.chain,
            residue.number,
            residue.insertion_code.unwrap_or(' ')
        )
        .unwrap();
    }
    writeln!(output).unwrap();
    writeln!(output, "[ bonds ]").unwrap();
    writeln!(output, "; ai aj funct b0(nm) kb(kJ/mol/nm^2)").unwrap();
    for bond in &system.bonds {
        if is_water_interaction(system, &bond.atoms) {
            continue;
        }
        writeln!(
            output,
            "{:>7} {:>7} 1 {:>14.8} {:>14.6}",
            bond.atoms[0] + 1,
            bond.atoms[1] + 1,
            bond.length / 10.0,
            2.0 * bond.force * 4.184 * 100.0
        )
        .unwrap();
    }
    writeln!(output).unwrap();
    writeln!(output, "[ angles ]").unwrap();
    writeln!(output, "; ai aj ak funct theta(deg) k(kJ/mol/rad^2)").unwrap();
    for angle in &system.angles {
        if is_water_interaction(system, &angle.atoms) {
            continue;
        }
        writeln!(
            output,
            "{:>7} {:>7} {:>7} 1 {:>14.8} {:>14.6}",
            angle.atoms[0] + 1,
            angle.atoms[1] + 1,
            angle.atoms[2] + 1,
            angle.radians.to_degrees(),
            2.0 * angle.force * 4.184
        )
        .unwrap();
    }
    writeln!(output).unwrap();
    writeln!(output, "[ dihedrals ]").unwrap();
    writeln!(output, "; ai aj ak al funct phase k multiplicity").unwrap();
    for dihedral in &system.dihedrals {
        writeln!(
            output,
            "{:>7} {:>7} {:>7} {:>7} {} {:>12.6} {:>12.6} {}",
            dihedral.atoms[0] + 1,
            dihedral.atoms[1] + 1,
            dihedral.atoms[2] + 1,
            dihedral.atoms[3] + 1,
            if dihedral.improper { 4 } else { 9 },
            dihedral.phase.to_degrees(),
            dihedral.force * 4.184,
            dihedral.periodicity
        )
        .unwrap();
    }
    let pairs = system
        .dihedrals
        .iter()
        .filter(|dihedral| !dihedral.improper)
        .map(|dihedral| {
            let first = dihedral.atoms[0].min(dihedral.atoms[3]);
            let second = dihedral.atoms[0].max(dihedral.atoms[3]);
            (first, second)
        })
        .collect::<BTreeSet<_>>();
    writeln!(output).unwrap();
    writeln!(output, "[ pairs ]").unwrap();
    for (first, second) in pairs {
        writeln!(output, "{:>7} {:>7} 1", first + 1, second + 1).unwrap();
    }
    writeln!(output).unwrap();
    writeln!(output, "[ settles ]").unwrap();
    writeln!(output, "; OW funct dOH(nm) dHH(nm)").unwrap();
    for residue in &system.residues {
        if residue.name == "WAT" && residue.atom_count == 3 {
            writeln!(
                output,
                "{:>7} 1 0.09572 0.151390065",
                residue.first_atom + 1
            )
            .unwrap();
        }
    }
    writeln!(output).unwrap();
    writeln!(output, "[ exclusions ]").unwrap();
    for residue in &system.residues {
        if residue.name == "WAT" && residue.atom_count == 3 {
            writeln!(
                output,
                "{} {} {}",
                residue.first_atom + 1,
                residue.first_atom + 2,
                residue.first_atom + 3
            )
            .unwrap();
        }
    }
    writeln!(output).unwrap();
    writeln!(output, "[ system ]").unwrap();
    writeln!(
        output,
        "GlySysBuilder solvated Amber ff14SB/GLYCAM06j-1 system"
    )
    .unwrap();
    writeln!(output).unwrap();
    writeln!(output, "[ molecules ]").unwrap();
    writeln!(output, "PreparedSystem 1").unwrap();
    output
}

pub(crate) fn write_gro(system: &System) -> String {
    let mut output = String::new();
    writeln!(output, "Generated by GlySysBuilder").unwrap();
    writeln!(output, "{}", system.atoms.len()).unwrap();
    for (index, atom) in system.atoms.iter().enumerate() {
        let residue = &system.residues[atom.residue];
        writeln!(
            output,
            "{:>5}{:<5}{:>5}{:>5}{:>8.3}{:>8.3}{:>8.3}",
            (atom.residue + 1) % 100_000,
            truncate(&residue.name, 5),
            truncate(&atom.name, 5),
            (index + 1) % 100_000,
            atom.position.x / 10.0,
            atom.position.y / 10.0,
            atom.position.z / 10.0
        )
        .unwrap();
    }
    writeln!(
        output,
        "{:>10.5}{:>10.5}{:>10.5}",
        system.box_angstrom[0] / 10.0,
        system.box_angstrom[1] / 10.0,
        system.box_angstrom[2] / 10.0
    )
    .unwrap();
    output
}

fn is_water_interaction<const N: usize>(system: &System, atoms: &[usize; N]) -> bool {
    atoms
        .iter()
        .all(|atom| system.residues[system.atoms[*atom].residue].name == "WAT")
}

fn truncate(value: &str, length: usize) -> &str {
    value.get(..value.len().min(length)).unwrap_or(value)
}
